---
auth:
  strategy: x509
  options:
    foo: bar
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0
    iface: eth0

ssh_key_path: ./mgmt.key
ignore_docker_version: false
authorization:
  mode: rbac
  options:

nodes:
  - address: 192.168.10.106
    user: rancher
    role: [worker]
    ssh_key_path: ./mgmt.key
  - address: 192.168.10.107
    user: rancher
    role: [worker]
    ssh_key_path: ./mgmt.key
  - address: 192.168.10.108
    user: rancher
    role: [worker]
    ssh_key_path: ./mgmt.key
  - address: 192.168.10.109
    user: rancher
    role: [controlplane, worker, etcd]
    ssh_key_path: ./mgmt.key
  - address: 192.168.10.110
    user: rancher
    role: [controlplane, worker, etcd]
    ssh_key_path: ./mgmt.key
  - address: 192.168.10.111
    user: rancher
    role: [controlplane, worker, etcd]
    ssh_key_path: ./mgmt.key

services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
    service_cluster_ip_range: 10.233.0.0/18
    pod_security_policy: false
    extra_args:
      v: 4
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_cidr: 10.233.64.0/18
    service_cluster_ip_range: 10.233.0.0/18
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
    cluster_domain: cluster.local
    cluster_dns_server: 10.233.0.3
    infra_container_image: gcr.io/google_containers/pause-amd64:3.0
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2

system_images:
  alpine: alpine:latest
  nginx_proxy: rancher/rke-nginx-proxy:0.1.0
  cert_downloader: rancher/rke-cert-deployer:0.1.0
  kubedns_image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
  dnsmasq_image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
  kubedns_sidecar_image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
  kubedns_autoscaler_image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.0.0